### ISSUE TITLE
Error building on windows :sad:

### ISSUE THREAD

**Issue by tarungarg546** [imagemin/imagemin-mozjpeg#18]
Hi i am trying to compressing `jpg` images on windows using this module and i am getting error as shown below :-

![capture](https://cloud.githubusercontent.com/assets/10435209/16995367/9c244b62-4ec9-11e6-822d-234b19374d13.PNG)

```
{ Error: Error in file: C:/image-minifier-sqd/build/src/1469033655787.pic1.jpg

Command failed: C:\windows\system32\cmd.exe /s /c ""C:\image-minifier-sqd\node_modules\mozjpeg\vendor\cjpeg.exe" "-outfile" "C:\Users\gargt\AppData\Local\Temp\a22b0277-9e36-4a65-bc19-773cd07077ec" "C:\Users\gargt\AppData\Local\Temp\4023421b-4a6b-4bd4-8df3-6e38c4b579b6""

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (C:\image-minifier-sqd\node_modules\cross-spawn-async\lib\enoent.js:37:29)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
  killed: false,
  code: 3221225477,
  signal: null,
  cmd: 'C:\\windows\\system32\\cmd.exe /s /c ""C:\\image-minifier-sqd\\node_modules\\mozjpeg\\vendor\\cjpeg.exe" "-outfile" "C:\\Users\\gargt\\AppData\\Local\\Temp\\a22b0277-9e36-4a65-bc19-773cd07077ec" "C:\\Users\\gargt\\AppData\\Local\\Temp\\4023421b-4a6b-4bd4-8df3-6e38c4b579b6""',
  stdout: '',
  stderr: '' }
```

My code for compressing image looks something like

```js
const imageminOptions = [
                    imageminMozjpeg(),
                    imageminPngquant({speed: 10}),
                    imageminSvgo(),
                    imageminGifsicle()
                  ];


function compressImage(filePath, stream, next) {
  return imagemin([filePath], 'build/dest',{
    plugins: imageminOptions
  })
  .then(file => {
    log(`Compressed and saved at location ${file[0].path}`);
    stream.push(file[0].path);
    next();
  })
  .catch(console.error);
}
```

PS :- Using imagemin plugin described on `npm`, i can get only `svg` compressing work rest of them show same errors.

**Comment by shinnn** [comment]
Should be reported on `mozjpeg-bin` issue tracker.
