### ISSUE TITLE
Fails to install on Arch Linux

### ISSUE THREAD

**Issue by mradzinski** [imagemin/imagemin-mozjpeg#19]
npm install throws:

```
  ⚠ The `/***/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -fiv && ./configure --disable-shared --prefix="/***/node_modules/mozjpeg/vendor" --bindir="/***/node_modules/mozjpeg/vendor" --libdir="/***/node_modules/mozjpeg/vendor" && make --jobs=4 && make install --jobs=4
Command failed: make install --jobs=4
/usr/bin/install: target 'website/node_modules/mozjpeg/vendor/libjpeg.la' is not a directory
make[2]: *** [Makefile:865: install-libLTLIBRARIES] Error 1
make[1]: *** [Makefile:2347: install-am] Error 2
make: *** [Makefile:2041: install-recursive] Error 1

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

**Comment by mradzinski** [comment]
FYI: Seems to be related to the directory name containing spaces.

**Comment by 1000ch** [comment]
It seems to be a dependency problem. Please try to install it regarding [the mozjpeg BUILDING instruction](https://github.com/mozilla/mozjpeg/blob/master/BUILDING.md).
