### ISSUE TITLE
Images being compressed to 0 bytes

### ISSUE THREAD

**Issue by josh18** [imagemin/imagemin-mozjpeg#4]
Not sure if I am doing something wrong but my images are being compressed to nothing. I've tried both:
```js
return gulp.src('src/img/*.jpg')
    .pipe(imagemin({
        use: [imageminMozjpeg()]
    }))
    .pipe(gulp.dest('dist/img'));
```
and
```js
return gulp.src('src/img/*.jpg')
    .pipe(imageminMozjpeg()())
    .pipe(gulp.dest('dist/img'));
```
with the same results. When using imagemin I get the message "Minified 2 images (saved 374.3 kB - 100%)".

Let me know if you need any more info from me.

**Comment by shinnn** [comment]
@josh18 Can you show us the image that causes this problem?

**Comment by josh18** [comment]
It's probably just my system, I don't plan on using this anymore so feel free to close this issue.

Just in case you want more info, when I try to install the plugin now via `npm install imagemin-mozjpeg` I get the error message:
```
The `/{removed_path}/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -fiv && ./configure --disable-shared --prefix="/{removed_path}/node_modules/mozjpeg/vendor" --bindir="/{removed_path}/node_modules/mozjpeg/vendor" --libdir="/{removed_path}/node_modules/mozjpeg/vendor" && make && make install
Command failed: /bin/sh -c autoreconf -fiv
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoconf --force
configure.ac:22: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/local/Cellar/autoconf/2.69/bin/autoconf failed with exit status: 1

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```
On OS X 10.7.5 (could well be the issue) and node v4.0.0.
