### ISSUE TITLE
Not working on FreeBSD

### ISSUE THREAD

**Issue by moroz** [imagemin/imagemin-mozjpeg#41]
Hello,
I am trying to build a Webpack bundle for my Phoenix project, and for research I decided to give it a shot on FreeBSD.
My application repo is [on Gitlab](https://gitlab.com/moroz2137/dw-taiwan), the webpack bundle is in `assets/` directory.
I have installed mozjpeg from BSD ports, and there is a `cjpeg` binary available:
```shell
$ cjpeg -V
Independent JPEG Group's CJPEG, version 8d  15-Jan-2012
Copyright (C) 2012, Thomas G. Lane, Guido Vollbeding
```
I know that `mozjpeg` is available in some way, because `image-webpack-loader` can use it and produces almost the same images as on my OSX machine. However, `image-webpack-loader` seems to only work with images that are imported in CSS, such as with `background-image`, and it doesn't optimise images copied over using CopyWebpackPlugin. I can't get these settings to run in Webpack on FreeBSD (Linux and OSX are fine):
```javascript
  plugins: [
    new MiniCssExtractPlugin({ filename: "../css/app.css" }),
    new CopyWebpackPlugin([{ from: "static/", to: "../" }]),
    new ImageminPlugin({
      test: /\.(jpe?g|png|gif|svg)$/i,
      plugins: [
        imageminMozjpeg({
          quality: 80,
          progressive: true
        })
      ]
    })
  ]
```
The first error is that there is no cjpeg binary in `vendor/`:
```shell
freebsd:~/dw-taiwan/assets$ yarn deploy
yarn run v1.17.3
$ webpack --mode production
Error: spawn /usr/home/deploy/dw-taiwan/assets/node_modules/mozjpeg/vendor/cjpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
When I create a symbolic link to the cjpeg binary installed in the system, it's no good either:
```shell
freebsd:~/dw-taiwan/assets$ ln -s /usr/local/bin/cjpeg /home/deploy/dw-taiwan/assets/node_modules/mozjpeg/vendor/cjpeg                       1
freebsd:~/dw-taiwan/assets$ yarn deploy
yarn run v1.17.3
$ webpack --mode production
Error: Unrecognized input file format --- perhaps you need -targa

    at /usr/home/deploy/dw-taiwan/assets/node_modules/execa/index.js:231:11
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Any suggestions on how this could be solved? I am really curious about FreeBSD and I hope I could help fix this problem.
Best regards,
KM

**Comment by frossi85** [comment]
@moroz Did you find any solution?

**Comment by moroz** [comment]
@frossi85 I think at the time I just left the images as is, without compression. Another quick and dirty workaround would be building assets in a continuous

**Comment by frossi85** [comment]
@moroz thanks for answering. My case is not exactly like yours I am trying to optimize images that where uploaded by my app users but having similar issues

**Comment by moroz** [comment]
Is imagemagick an option? I think I had it working on FreeBSD under Elixir.
