### ISSUE TITLE
unhandledRejection resulting in crash when compressing jpg

### ISSUE THREAD

**Issue by BradBailey-web** [imagemin/imagemin-mozjpeg#51]
The .jpg file that it crashes with is attached. Before hitting this error, it had compressed approximately 100-125 images successfully. This could be a problem on my side of things, I do not have error handling set up (for mozjpeg), as there is no documentation that I could find that explained how I should attempt this.

![item-1gxfo9](https://user-images.githubusercontent.com/62399085/83339153-d5d0d200-a27f-11ea-9772-79e9afb313e6.jpg)

This is my server output (pm2 logs) when mozjpeg crashes (using asterisks in place of relative paths and pm2 server names):

0|*  | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|*  | Error: Command was killed with SIGKILL (Forced termination): /home/*/*/node_modules/mozjpeg/vendor/cjpeg -quality 40 -maxmemory 20000000
0|*  |     at makeError (/home/*/*/node_modules/imagemin-mozjpeg/node_modules/execa/lib/error.js:59:11)
0|*  |     at handlePromise (/home/*/*/node_modules/imagemin-mozjpeg/node_modules/execa/index.js:114:26)
0|*  |     at runMicrotasks (<anonymous>)
0|*  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
0|*  |     at async /home/*/*/node_modules/imagemin-mozjpeg/index.js:109:19
0|*  |     at async /home/*/*/node_modules/p-pipe/index.js:12:19
0|*  |     at async handleFile (/home/*/*/node_modules/imagemin/index.js:21:9)
0|*  |     at async /home/*/*/node_modules/imagemin/index.js:54:13
0|*  |     at async Promise.all (index 0)
0|*  |     at async /home/*/*/routes/admin.js:56:29

After this error, it begins logging binary (well the ascii interpretation of it at least) 

And finally it fataly crashes the pm2 server to the point where I need to restart it using my ecosystem.config file (pm2 is not able to restart itself)

**Comment by frossi85** [comment]
I am experiencing the same using the same libs versions while running on Linux Alpine but not on Mac OSX. Does anyone have an idea of how to make this library work with Alpine Linux? I tried everything that I read on the different issues but nothing helped. I always got some error (different for each solution that I found on previous issues)

**Comment by SMKH-PRO** [comment]
I am facing some problem on Windows 10.
 happening with pngs too.

Working perfectly on MacOSX

**Comment by Dudeful** [comment]
I was probably having the same issue yesterday, here is a [possible solution](https://github.com/imagemin/imagemin/issues/363#issuecomment-748877383)
