### ISSUE TITLE
TypeError: options.sample.join is not a function

### ISSUE THREAD

**Issue by davidenco** [imagemin/imagemin-mozjpeg#59]
Using v9.0.0 and trying to set "sample" option but getting a TypeError:

# imagemin images/photo.jpg --plugin.mozjpeg.quality=75 --plugin.mozjpeg.sample=2x2
TypeError: options.sample.join is not a function
    at /usr/lib/node_modules/imagemin-mozjpeg/index.js:106:39
    at /usr/lib/node_modules/imagemin-cli/node_modules/p-pipe/index.js:12:25
    at handleFile (/usr/lib/node_modules/imagemin-cli/node_modules/imagemin/index.js:21:54)
    at async /usr/lib/node_modules/imagemin-cli/node_modules/imagemin/index.js:54:13
    at async Promise.all (index 0)
    at async run (/usr/lib/node_modules/imagemin-cli/cli.js:90:11)
    at async /usr/lib/node_modules/imagemin-cli/cli.js:122:3

**Comment by davidenco** [comment]
Operator error!
