### ISSUE TITLE
mozjpeg@5.0 postinstall fails 

### ISSUE THREAD

**Issue by alchemist-bounty** [imagemin/imagemin-mozjpeg#74]
I am using Docker with WSL2

I am trying to install mozjpeg@5.0 but it fails.
I am using node version 12.22.6 and npm version 6.14.15

`root@4cb8433389a7:/var/www/html# DEBUG=* npm install mozjpeg@5.0 --verbose
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/root/.nvm/versions/node/v12.22.6/bin/node',
npm verb cli   '/root/.nvm/versions/node/v12.22.6/bin/npm',
npm verb cli   'install',
npm verb cli   'mozjpeg@5.0',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@6.14.15
npm info using node@v12.22.6
npm verb npm-session 61c8c8dea63dcd87
npm http fetch GET 304 https://registry.npmjs.org/mozjpeg 2818ms (from cache)
npm timing stage:loadCurrentTree Completed in 16528ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 27ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 1053ms
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 5536ms
npm timing stage:loadIdealTree Completed in 7038ms
npm timing stage:generateActionsToTake Completed in 2186ms
npm verb correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /root/.npm/_locks/staging-44e6ff01005ebe4d.lock for /var/www/html/node_modules/.staging
npm timing action:extract Completed in 208ms
npm timing action:finalize Completed in 98ms
npm timing action:refresh-package-json Completed in 78ms
npm info lifecycle mozjpeg@5.0.0~preinstall: mozjpeg@5.0.0
npm timing action:preinstall Completed in 3ms
npm info linkStuff mozjpeg@5.0.0
npm verb linkBins [ { mozjpeg: 'cli.js' }, '/var/www/html/node_modules/.bin', false ]
npm timing action:build Completed in 29ms
npm info lifecycle mozjpeg@5.0.0~install: mozjpeg@5.0.0
npm timing action:install Completed in 3ms
npm info lifecycle mozjpeg@5.0.0~postinstall: mozjpeg@5.0.0

> mozjpeg@5.0.0 postinstall /var/www/html/node_modules/mozjpeg
> node lib/install.js

  ⚠ The `/var/www/html/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:182:17)
Emitted 'error' event on Unzip instance at:
    at Zlib.zlibOnError [as onerror] (zlib.js:185:8) {
  errno: -5,
  code: 'Z_BUF_ERROR'
}
npm verb lifecycle mozjpeg@5.0.0~postinstall: unsafe-perm in lifecycle false
npm verb lifecycle mozjpeg@5.0.0~postinstall: PATH: /root/.nvm/versions/node/v12.22.6/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/html/node_modules/mozjpeg/node_modules/.bin:/var/www/html/node_modules/.bin:/root/.nvm/versions/node/v12.22.6/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
npm verb lifecycle mozjpeg@5.0.0~postinstall: CWD: /var/www/html/node_modules/mozjpeg
npm timing audit submit Completed in 1326ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 1581ms
npm timing audit body Completed in 257ms
npm info lifecycle mozjpeg@5.0.0~postinstall: Failed to exec postinstall script
npm timing action:postinstall Completed in 14368ms
npm verb unlock done using /root/.npm/_locks/staging-44e6ff01005ebe4d.lock for /var/www/html/node_modules/.staging
npm timing stage:rollbackFailedOptional Completed in 145ms
npm timing stage:runTopLevelLifecycles Completed in 41080ms
npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.5.2 requires a peer of popper.js@^1.16.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64

npm verb stack Error: mozjpeg@5.0.0 postinstall: `node lib/install.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v12.22.6/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:314:20)
npm verb stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v12.22.6/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:314:20)
npm verb stack     at maybeClose (internal/child_process.js:1022:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
npm verb pkgid mozjpeg@5.0.0
npm verb cwd /var/www/html
npm verb Linux 5.10.16.3-microsoft-standard-WSL2
npm verb argv "/root/.nvm/versions/node/v12.22.6/bin/node" "/root/.nvm/versions/node/v12.22.6/bin/npm" "install" "mozjpeg@5.0" "--verbose"
npm verb node v12.22.6
npm verb npm  v6.14.15
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mozjpeg@5.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mozjpeg@5.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 41866ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-01-05T17_24_58_015Z-debug.log`

**Comment by alchemist-bounty** [comment]
And I have no idea why some of output has strike after I submit the issue above

**Comment by alchemist-bounty** [comment]
Solved this issue by install mozjpeg and link mozjpeg/cjpeg and mozjpeg/djpeg in usr/bin
