### ISSUE TITLE
Images being compressed to 0 bytes

### ISSUE THREAD

**Issue by scottzirkel** [imagemin/imagemin-mozjpeg#8]
I'm having the exact same issue as #4, only I'm running the latest OSX (I believe they were on 10.7).

It seems to be an issue at npm install and it affects any jpg I try.

At install I'm getting the following error (again, the same as #4)
````
> mozjpeg@4.1.1 postinstall /Users/me/Development/website/node_modules/imagemin-mozjpeg/node_modules/mozjpeg
> node lib/install.js

  ⚠ The `/Users/me/Development/website/node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -fiv && ./configure --disable-shared --prefix="/Users/me/Development/website/node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor" --bindir="/Users/me/Development/website/node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor" --libdir="/Users/me/Development/website/node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor" && make --jobs=8 && make install --jobs=8
Command failed: /bin/sh -c ./configure --disable-shared --prefix="/Users/me/Development/website/node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor" --bindir="/Users/me/Development/website/node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor" --libdir="/Users/me/Development/website/node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor"
configure: error: installation or configuration problem: assembler cannot create object files.

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
imagemin-mozjpeg@5.1.0 node_modules/imagemin-mozjpeg
├── is-jpg@1.0.0
├── through2@0.6.5 (xtend@4.0.1, readable-stream@1.0.33)
└── mozjpeg@4.1.1 (logalot@2.1.0, bin-wrapper@3.0.2, bin-build@2.2.0)
````

I have tried to install it fresh, as well as from an existing package.json. I've also created a new directory and tried there.

**Comment by shinnn** [comment]
This is a mozjpeg-bin issue.
